name: Build rtl_433 images

on:
  push:
  pull_request:
  release:
    types: ["published"]

jobs:
  build:
    name: Build ${{ matrix.arch }} ${{ matrix.service }} addon
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # arch: ["linux/armhf", "linux/armv7", "linux/aarch64", "linux/amd64", "linux/i386"]
        service: ["rtl_433", "rtl_433_mqtt_autodiscovery"]

    steps:
#    -
#      name: Set up QEMU
#      uses: docker/setup-qemu-action@v1

    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./${{ matrix.service }}
        platforms: linux/amd64,linux/arm64
        push: false
        tags: |
          ghcr.io/pbkhrv/rtl_433-hass-addons:latest
