name: Build rtl_433 images

on:
  push:
  pull_request:

jobs:
  build:
    name: Build rtl_433 addon
    runs-on: ubuntu-latest

    steps:

    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: {{defaultContext}}:rtl_433
        platforms: linux/amd64,linux/arm64
        push: false
        tags: |
          ghcr.io/pbkhrv/rtl_433-hass-addons:latest
