name: Build rtl_433 images

on:
  push:
  pull_request:
  release:
    types: ["published"]

jobs:
  build_rtl_433:
    name: Build rtl_433 addon
    runs-on: ubuntu-latest

    steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v4

    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Test build
      uses: home-assistant/builder@master
      with:
        args: |
          --test \
          --all \
          --version $GITHUB_REF_SLUG \
          --target rtl_433

  build_rtl_433_mqtt_autodiscovery:
    name: Build rtl_433_mqtt_autodiscovery addon
    runs-on: ubuntu-latest

    steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v4

    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Test build
      uses: home-assistant/builder@master
      with:
        args: |
          --test \
          --all \
          --version $GITHUB_REF_SLUG \
          --target rtl_433_mqtt_autodiscovery
